export const FETCH_ISSUES           = 'MAIN_PAGE/FETCH_ISSUES'
export const FETCH_ISSUES_FULFILLED = 'MAIN_PAGE/FETCH_ISSUES_FULFILLED'
export const FETCH_ISSUES_REJECTED  = 'MAIN_PAGE/FETCH_ISSUES_REJECTED'

export const CLEAR_DATA = 'MAIN_PAGE/CLEAR_DATA'
export const CLEAR_ISSUES = 'MAIN_PAGE/CLEAR_ISSUES'

export const FETCH_REPOS = 'MAIN_PAGE/FETCH_REPOS'
export const FETCH_REPOS_FULFILLED = 'MAIN_PAGE/FETCH_REPOS_FULFILLED'
export const FETCH_REPOS_REJECTED = 'MAIN_PAGE/FETCH_REPOS_REJECTED'
