export const FETCH_REPO               = 'ISSUE_PAGE/FETCH_REPO'
export const FETCH_REPO_FULFILLED     = 'ISSUE_PAGE/FETCH_REPO_FULFILLED'
export const FETCH_REPO_REJECTED     = 'ISSUE_PAGE/FETCH_REPO_REJECTED'

export const FETCH_ISSUE             = 'ISSUE_PAGE/FETCH_ISSUE'
export const FETCH_ISSUE_WITH_BUFFER = 'ISSUE_PAGE/FETCH_ISSUE_WITH_BUFFER'
export const FETCH_ISSUE_FULFILLED   = 'ISSUE_PAGE/FETCH_ISSUE_FULFILLED'
export const FETCH_ISSUE_REJECTED    = 'ISSUE_PAGE/FETCH_ISSUE_REJECTED'

export const FETCH_COMMENTS              = 'ISSUE_PAGE/FETCH_COMMENTS'
export const FETCH_COMMENTS_WITH_BUFFER  = 'ISSUE_PAGE/FETCH_COMMENTS_WITH_BUFFER'
export const FETCH_COMMENTS_FULFILLED    = 'ISSUE_PAGE/FETCH_COMMENTS_FULFILLED'
export const FETCH_COMMENTS_REJECTED     = 'ISSUE_PAGE/FETCH_COMMENTS_REJECTED'
